### ISSUE TITLE
L4 и L5

### ISSUE THREAD

**Issue by vv12131415** [LaravelRUS/awesome-laravel-rus#1]
Считаю что нужно поделить материал (или даже засунуть в разные ветки) по L4 и L5. А то намешано всего в кучу

**Comment by ghost** [comment]
Согласен, 
Впрочем, ссылок на материалы **только** по Laravel 4 не так много.
И вряд ли для их наличия в подборке остался какой-то практический смысл. Изучать фрейм по ним уже никто не будет в связи с не актуальностью Laravel 4. В подборке они остались скорее просто по историческим причинам. =)

Поэтому, полагаю, что можно просто почистить список от ссылок с явно устаревшей информацией.

**Comment by ghost** [comment]
Создал [архивную ветку](https://github.com/LaravelRUS/awesome-laravel-rus/tree/archived-l4) , включающую материалы по Laravel 4. =)
Пополнять ее уже вряд ли кто будет. Но пусть хоть на память останется)

Мастер-ветку теперь можно смело чистить, если никто не против.)
